name: Build del proyecto

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Compilar y analizar
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restaurar dependencias
        run: dotnet restore core/workers/workers.sln

      - name: Compilar
        run: dotnet build core/workers/workers.sln --configuration Release
