name: Unit Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    name: Compilar y analizar
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restaurar dependencias (unit-testing)
        run: dotnet restore csharp/unit-testing/UnitTesting.sln
        
      - name: Compilar
        run: dotnet build csharp/unit-testing/UnitTesting.sln --configuration Release

      - name: Ejecutar pruebas unitarias
        run: dotnet test csharp/unit-testing/UnitTesting.sln --configuration Release --results-directory ./coverage

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
  
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
